-- Produtos extraídos do Catálogo OLI Vinhos - v2026.v5.pdf.
-- Estoque permanece NULL porque o PDF não informa quantidades.
insert into public.products (name,slug,producer,country,region,type,grape,grape_composition,vintage,volume,alcohol_content,classification,description,pairing,normal_price,promotional_price,quantity_available,image_url,featured,active,information_source)
values
('7Colores Cabernet Sauvignon','7colores-cabernet-sauvignon','7Colores','Chile','Valle Central','Tinto','Cabernet Sauvignon','Cabernet Sauvignon',2022,'750 ml','13%',null,null,null,30,null,null,'/products/7colores-cabernet-sauvignon.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('7Colores Cortejo Carmenère','7colores-cortejo-carmenere','7Colores','Chile','Valle Central','Tinto','Carmenère','85% Carmenère, 15% Cabernet Sauvignon',2022,'750 ml','13%','Linha Cortejo','Breve estágio em tanques de aço inox.','Embutidos, legumes grelhados, quiches e roast beef.',30,null,null,'/products/7colores-cortejo-carmenere.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('7Colores Gran Reserva Pinot Noir / Sémillon','7colores-gran-reserva-pinot-noir-semillon','7Colores','Chile','Valle de Casablanca','Tinto','Pinot Noir','96% Pinot Noir e 4% Sémillon',2021,'750 ml','13,5%','Gran Reserva','12 meses em barrica de carvalho francês.','Pizzas com queijos, entradas frias, roast beef, embutidos e aves.',50,null,null,'/products/7colores-gran-reserva-pinot-noir-semillon.webp',true,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Caviro Musiolo Vino Bianco','caviro-musiolo-vino-bianco','Caviro','Itália','Emilia-Romagna','Branco','Trebbiano','Trebbiano, Moscato, Malvasia e outras variedades italianas',2020,'750 ml','10,8%','Linha Musiolo','Breve estágio em tanques de inox.','Como aperitivo, com bacalhau ou spaghetti com vôngole.',76,30,null,'/products/caviro-musiolo-vino-bianco.webp',true,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Conto Alentejano Branco','conto-alentejano-branco','Conto','Portugal','Alentejo','Branco','Arinto','Arinto e Antão Vaz',2020,'750 ml','12,5%',null,'Breve estágio em tanques de aço inox antes do engarrafamento.','Saladas, salmão defumado e risotos.',35,null,null,'/products/conto-alentejano-branco.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Conto Alentejano Tinto','conto-alentejano-tinto','Conto','Portugal','Alentejo','Tinto','Trincadeira','Trincadeira, Touriga Nacional, Syrah e Aragonez',2018,'750 ml','13%',null,'Breve estágio em tanques de aço inox antes do engarrafamento.','Carnes vermelhas, cogumelos, trufas e queijos de média cura.',30,null,null,'/products/conto-alentejano-tinto.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Norton 1895 Cabernet Sauvignon','norton-1895-cabernet-sauvignon','Bodega Norton','Argentina','Mendoza','Tinto','Cabernet Sauvignon','Cabernet Sauvignon',2021,'750 ml','14%','Linha 1895','Breve estágio em tanques de aço inox.','Carnes suculentas ou com molho denso, parmesão, gouda curado e copa.',30,null,null,'/products/norton-1895-cabernet-sauvignon.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Norton 1895 Malbec','norton-1895-malbec','Bodega Norton','Argentina','Mendoza','Tinto','Malbec','100% Malbec',2021,'750 ml','13,9%','Linha 1895','Breve estágio em tanques de aço inox.','Carnes em conserva, embutidos, tutu com bisteca de porco e carne de panela.',30,null,null,'/products/norton-1895-malbec.webp',true,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Norton 1895 Torrontés','norton-1895-torrontes','Bodega Norton','Argentina','Mendoza','Branco','Torrontés','100% Torrontés',2021,'750 ml','13%','Linha 1895','Breve estágio em tanques de aço inox.','Saladas verdes, frutas secas e sementes, ou como aperitivo.',30,null,null,'/products/norton-1895-torrontes.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Norton Cosecha Tardia Branco','norton-cosecha-tardia-branco','Bodega Norton','Argentina','Mendoza','Branco','Chardonnay','100% Chardonnay',2021,'750 ml','11,2%','Cosecha Tardia','Não passa por afinamento em madeira.','Tortas doces de frutas, petit four ou sozinho como sobremesa.',30,null,null,'/products/norton-cosecha-tardia-branco.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Pacheco Pereda Rosado','pacheco-pereda-rosado','Pacheco Pereda','Argentina','Mendoza','Rosé','Sangiovese','58% Sangiovese e 42% Syrah',2022,'750 ml','12,5%','Varietal','Sem amadurecimento.','Carnes leves, legumes da estação assados e massas com molhos leves.',30,null,null,'/products/pacheco-pereda-rosado.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Perdriel Series Cabernet Sauvignon','perdriel-series-cabernet-sauvignon','Finca Perdriel','Argentina','Mendoza','Tinto','Cabernet Sauvignon','100% Cabernet Sauvignon',2019,'750 ml','14,5%','Series','10 meses em barricas de carvalho francês de primeiro e segundo usos, seguidos por 10 meses em garrafa.','Pratos potentes, carnes de caça, assados, ossobuco e queijos de massa dura.',80,null,null,'/products/perdriel-series-cabernet-sauvignon.webp',true,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Frescobaldi Remole Bianco Toscana IGT','frescobaldi-remole-bianco-toscana-igt','Frescobaldi','Itália','Toscana','Branco','Vermentino','Vermentino e Trebbiano',2022,'750 ml','12%','Toscana IGT - Tenuta Rèmole','Quatro meses em tanques de aço inox com temperatura controlada.','Como aperitivo, com saladas, peixes, frutos do mar e carnes brancas.',80,null,null,'/products/frescobaldi-remole-bianco.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Frescobaldi Remole Rosato Toscana IGT','frescobaldi-remole-rosato-toscana-igt','Frescobaldi','Itália','Toscana','Rosé','Sangiovese','100% Sangiovese',2022,'750 ml','12%','Toscana IGT - Tenuta Rèmole','Quatro meses em tanques de aço inox com temperatura controlada.','Como aperitivo, com entradas, peixes ou vegetais.',80,null,null,'/products/frescobaldi-remole-rosato.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Frescobaldi Ammiraglia Alìe Rosé','frescobaldi-ammiraglia-alie-rose','Frescobaldi','Itália','Toscana','Rosé','Syrah','75% Syrah e 25% Vermentino',2022,'750 ml','12%','Tenuta Ammiraglia','Quatro meses em tanques de aço e um mês em garrafa.','Frutos do mar marinados, como ceviche, grelhados ou fritos.',150,null,null,'/products/frescobaldi-alie-rose.webp',true,true,'Catálogo OLI Vinhos - v2026.v5.pdf'),
('Rocchetta Dolcetto d''Alba','rocchetta-dolcetto-dalba','Marchesi Incisa della Rocchetta','Itália','Piemonte','Tinto','Dolcetto','100% Dolcetto',2019,'750 ml','14%','Dolcetto d''Alba','Estágio em tanques de aço inox e, em parte, grandes tonéis de carvalho.','Molhos de tomate sem pescados, carnes cruas como tartar, embutidos e queijos de meia cura ou curados.',100,null,null,'/products/rocchetta-dolcetto-dalba.webp',false,true,'Catálogo OLI Vinhos - v2026.v5.pdf')
on conflict (slug) do update set
  name=excluded.name, producer=excluded.producer, country=excluded.country, region=excluded.region,
  type=excluded.type, grape=excluded.grape, grape_composition=excluded.grape_composition,
  vintage=excluded.vintage, volume=excluded.volume, alcohol_content=excluded.alcohol_content,
  classification=excluded.classification, description=excluded.description, pairing=excluded.pairing,
  normal_price=excluded.normal_price, promotional_price=excluded.promotional_price,
  image_url=excluded.image_url, featured=excluded.featured, information_source=excluded.information_source;

